# Streamlit Cloud Secrets Configuration
# Copy this file to your Streamlit Cloud app's secrets section

# Database Configuration (Required for Streamlit Cloud)
[database]
host = "your-database-host.com"
port = "5432"
database = "sam_contracts"
username = "your-username"
password = "your-password"

# API Keys
SAM_API_KEY = "your-sam-api-key-here"
SLACK_WEBHOOK_URL = "your-slack-webhook-url-here"

# Optional Configuration
API_KEY_EXPIRATION_DATE = "2025-12-21"
GOVCON_MODEL_PATH = "mistral-7b-instruct-v0.1.Q4_K_M.gguf"
