# Database Configuration - Local Docker
[database]
host = "localhost"
port = "5434"
database = "sam_contracts"
username = "postgres"
password = "mysecretpassword"

# API Keys
SAM_API_KEY = "d57QFEQCIIdegq3Y2nndqD4iyruX5ktwEXSev7MG"
SLACK_WEBHOOK_URL = "https://hooks.slack.com/services/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"

# Optional Configuration
API_KEY_EXPIRATION_DATE = "2025-12-21"
GOVCON_MODEL_PATH = "mistral-7b-instruct-v0.1.Q4_K_M.gguf"

# Phase 3 & 4: Email and Document Generation
SENDGRID_API_KEY = "your_sendgrid_api_key_here"
SENDGRID_FROM_EMAIL = "your_email@company.com"
SENDGRID_FROM_NAME = "GovCon Suite"

# Application URLs
BASE_URL = "http://localhost:8502"
PARTNER_PORTAL_URL = "http://localhost:8502/partner_portal"

# Company Information for Documents
COMPANY_NAME = "Your Company Name"
COMPANY_ADDRESS = "Your Company Address"
COMPANY_PHONE = "Your Company Phone"
COMPANY_EMAIL = "your_email@company.com"